mutt              = "${HOME}/.muttrc"
git               = "${HOME}/.gitconfig"
top               = "${HOME}/.toprc"
tmux              = "${HOME}/.tmux.conf"
screen            = "${HOME}/.screenrc"
starship          = "${HOME}/.config/starship.toml"
efmLanguageServer = "${HOME}/.config/efm-langserver/config.yaml"
clangFormat       = "${HOME}/.clang-format"
clangTidy         = "${HOME}/.clang-tidy"
bash              = "${HOME}/.bashrc"

[mpv]
linux   = "${HOME}/.config/mpv/mpv.conf"
windows = "${env:APPDATA}\\mpv\\mpv.conf"
macos   = "${HOME}/.config/mpv/mpv.conf"

[clangd]
linux   = "${HOME}/.config/clangd/config.yaml"
windows = "${env:LOCALAPPDATA}\\clangd\\config.yaml"
macos   = "${HOME}/Library/Preferences/clangd/config.yaml"

[conemu]
linux   = ""
windows = "${env:APPDATA}\\ConEmu.xml"
macos   = ""

[windowsTerminal]
linux   = ""
windows = "${env:LOCALAPPDATA}\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\settings.json"
macos   = ""

[gpg]
linux   = "${HOME}/.gnupg/gpg.conf"
windows = "${env:APPDATA}\\gnupg\\gpg.conf"
macos   = "${HOME}/.gnupg/gpg.conf"

[pwsh]
linux   = "${HOME}/.config/powershell/profile.ps1"
windows = "${profile}"
macos   = "${HOME}/.config/powershell/profile.ps1"

[playlistDir]
linux   = "${HOME}/.config/mps-youtube"
windows = "${env:APPDATA}\\mps-youtube"
macos   = "${HOME}/.config/mps-youtube"
