[target]
playlistDir = ""

mutt              = ""
git               = ""
top               = ""
tmux              = ""
screen            = ""
mpv               = ""
starship          = ""
efmLanguageServer = ""
conemu            = ""

[install]
mutt              = true
git               = true
top               = true
tmux              = true
screen            = true
mpv               = true
starship          = true
efmLanguageServer = true
conemu            = true
playlist          = true

[source]
playlistDir = "MpsytPlaylist"

mutt              = ".muttrc"
git               = ".gitconfig"
top               = ".toprc"
tmux              = ".tmux.conf"
screen            = ".screenrc"
mpv               = "mpv.conf"
starship          = "starship.toml"
efmLanguageServer = "efmLanguageServer.yaml"
conemu            = "ConEmu.xml"
playlist          = [
  "favorite.m3u",
  "fullMetalAlchemist.m3u",
  "letterBee.m3u",
  "pokemon.m3u",
  "rebron.m3u",
  "shana.m3u",
]
