[branch]
main  = "master"
local = "local"

[target]
playlistDir = ""

mutt              = ""
git               = ""
top               = ""
tmux              = ""
screen            = ""
mpv               = ""
ytdlp             = ""
starship          = ""
efmLanguageServer = ""
conemu            = ""
windowsTerminal   = ""
clangd            = ""
clangFormat       = ""
clangTidy         = ""
gpg               = ""
pwsh              = ""
bash              = ""
readline          = ""

[install]
mutt              = true
git               = true
top               = true
tmux              = true
screen            = true
mpv               = true
ytdlp             = true
starship          = true
efmLanguageServer = true
conemu            = true
windowsTerminal   = true
clangd            = true
clangFormat       = true
clangTidy         = true
gpg               = true
pwsh              = true
bash              = true
readline          = true
playlist          = true

[source]
playlistDir = "Settings/MpsytPlaylist"

mutt              = "Settings/.muttrc"
git               = "Settings/.gitconfig"
top               = "Settings/.toprc"
tmux              = "Settings/.tmux.conf"
screen            = "Settings/.screenrc"
mpv               = "Settings/mpv.conf"
ytdlp             = "Settings/yt-dlp.conf"
starship          = "Settings/starship.toml"
efmLanguageServer = "Settings/efmLanguageServer.yaml"
conemu            = "Settings/ConEmu.xml"
windowsTerminal   = "Settings/windowsTerminalSettings.json"
clangd            = "Settings/clangd.yaml"
clangFormat       = "Settings/.clang-format"
clangTidy         = "Settings/.clang-tidy"
gpg               = "Settings/gpg.conf"
pwsh              = "Settings/profile.ps1"
bash              = "Settings/.bashrc"
readline          = "Settings/.inputrc"
playlist          = [
  "favorite.m3u",
  "fullMetalAlchemist.m3u",
  "letterBee.m3u",
  "pokemon.m3u",
  "reborn.m3u",
  "shana.m3u",
  "girlsLastTour.m3u",
  "haikyu.m3u",
  "hikarusGo.m3u",
  "railgun.m3u",
  "takagisan.m3u",
]
