[target]
playlistDir = ""

mutt              = ""
git               = ""
top               = ""
tmux              = ""
screen            = ""
mpv               = ""
starship          = ""
efmLanguageServer = ""
conemu            = ""
windowsTerminal   = ""

[install]
mutt              = true
git               = true
top               = true
tmux              = true
screen            = true
mpv               = true
starship          = true
efmLanguageServer = true
conemu            = true
windowsTerminal   = true
playlist          = true

[source]
playlistDir = "Settings/MpsytPlaylist"

mutt              = "Settings/.muttrc"
git               = "Settings/.gitconfig"
top               = "Settings/.toprc"
tmux              = "Settings/.tmux.conf"
screen            = "Settings/.screenrc"
mpv               = "Settings/mpv.conf"
starship          = "Settings/starship.toml"
efmLanguageServer = "Settings/efmLanguageServer.yaml"
conemu            = "Settings/ConEmu.xml"
windowsTerminal   = "Settings/windowsTerminalSettings.json"
playlist          = [
  "favorite.m3u",
  "fullMetalAlchemist.m3u",
  "letterBee.m3u",
  "pokemon.m3u",
  "rebron.m3u",
  "shana.m3u",
]
